# Enhanced .NET Build and Test Workflow with Beautiful Reporting
# Based on: https://seankilleen.com/2024/03/beautiful-net-test-reports-using-github-actions/

name: .NET Build & Test with Reports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions: write-all  # Required for PR comments and test reports

    steps:
    - name: Check out the code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for better reporting
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Debug
      
    - name: Run Tests with Coverage
      run: dotnet test --configuration Debug --verbosity normal --settings coverlet.runsettings --collect:"XPlat Code Coverage"
      
    - name: Combine Coverage Reports
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
      with:
        reports: "**/TestResults/**/coverage.cobertura.xml"
        targetdir: "${{ github.workspace }}"
        reporttypes: "Cobertura"
        verbosity: "Info"
        title: "Fantasy Shop Keeper - Code Coverage"
        tag: "${{ github.run_number }}_${{ github.run_id }}"
        
    - name: Upload Combined Coverage XML
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ${{ github.workspace }}/Cobertura.xml
        retention-days: 30
        
    - name: Upload Test Result Files
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ${{ github.workspace }}/TestResults/**/*
        retention-days: 30
        
    - name: Generate Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: "Cobertura.xml"
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: "60 80"  # Warning at 60%, good at 80%
        
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
        
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.16.1
      if: always()  # Run even if tests fail
      with:
        trx_files: "${{ github.workspace }}/TestResults/**/*.trx"
        comment_title: "🧪 Fantasy Shop Keeper Test Results"
        check_name: "Test Results"
        fail_on: "test failures"
        action_fail: true
        action_fail_on_inconclusive: true
